"""create_steam_user_and_app_tables

Revision ID: f22fa287ea77
Revises: 293ea0e6c696
Create Date: 2025-05-18 14:03:35.211536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f22fa287ea77'
down_revision: Union[str, None] = '293ea0e6c696'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('steamApp',
    sa.Column('appid', sa.Integer(), nullable=False),
    sa.Column('appName', sa.String(length=100), nullable=False),
    sa.Column('playtime', sa.Integer(), nullable=False),
    sa.Column('lastPlayed', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('appid')
    )
    op.create_index(op.f('ix_steamApp_appid'), 'steamApp', ['appid'], unique=False)
    op.create_table('steamUser',
    sa.Column('steamid', sa.Integer(), nullable=False),
    sa.Column('personaName', sa.String(length=10), nullable=False),
    sa.Column('profileURL', sa.String(length=100), nullable=False),
    sa.Column('avatar', sa.String(length=200), nullable=True),
    sa.Column('timeCreated', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('steamid')
    )
    op.create_index(op.f('ix_steamUser_steamid'), 'steamUser', ['steamid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_steamUser_steamid'), table_name='steamUser')
    op.drop_table('steamUser')
    op.drop_index(op.f('ix_steamApp_appid'), table_name='steamApp')
    op.drop_table('steamApp')
    # ### end Alembic commands ###
